### ISSUE TITLE
遇到一个奇怪的问题

### ISSUE THREAD

**Issue by zypperin** [medcl/elasticsearch-analysis-pinyin#20]
配置：
```yml
pinyin_ik_first_letter:
        type: custom
        tokenizer: ik
        filter:
        - pinyin_first_letter
        - lowercase
        - unique
```

测试：
GET /test/_analyze?text=abc北京天安门&analyzer=pinyin_ik_first_letter&pretty

```json
{
  "tokens" : [ {
    "token" : "",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "ENGLISH",
    "position" : 1
  }, {
    "token" : "bj",
    "start_offset" : 3,
    "end_offset" : 5,
    "type" : "CN_WORD",
    "position" : 2
  }, {
    "token" : "j",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "CN_WORD",
    "position" : 3
  }, {
    "token" : "tam",
    "start_offset" : 5,
    "end_offset" : 8,
    "type" : "CN_WORD",
    "position" : 4
  }, {
    "token" : "ta",
    "start_offset" : 5,
    "end_offset" : 7,
    "type" : "CN_WORD",
    "position" : 5
  }, {
    "token" : "m",
    "start_offset" : 7,
    "end_offset" : 8,
    "type" : "CN_CHAR",
    "position" : 6
  } ]
}
```

abc 不见了，是什么原因呀？
